[pytest]
# Zawsze uruchamiaj testy w trybie verbose (szczegółowym), pokazując nazwy testów
addopts = -v

# Rejestracja własnych znaczników, aby pozbyć się ostrzeżeń (warnings)
markers =
    matematyka: Testy dotyczące algebry (Ciało Galois, Reed-Solomon)
    integracyjne: Wolniejsze testy sprawdzające cały cykl (np. skanowanie z pliku)
    dekoder: Testy samego wyciągania bitów i zrzucania masek